---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Disable e-mail notifications on jail stop and start
  ansible.builtin.copy:
    src: "files/action.d/sendmail-common.local"
    dest: "/etc/fail2ban/action.d/sendmail-common.local"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart fail2ban

- name: Install the jail.local file
  ansible.builtin.template:
    src: "jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart fail2ban

- name: Make sure the fail2ban systemd service is enabled and started
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Check the fail2ban service status
  register: fail2ban_service
  ansible.builtin.systemd_service:
    name: fail2ban

- name: Fail if fail2ban failed
  failed_when: fail2ban_failed and not letsencrypt_staging
  register: fail2ban_failed
  ansible.builtin.assert:
    that: fail2ban_service.status.StatusErrno != "0"
